### ISSUE TITLE
QIR-Runner and the use of custom external declarations

### ISSUE THREAD

**Issue by wongey** [qir-alliance/qir-runner#75]
This question and answer is posted here for reference. However, any further discussion will be welcomed.

I was not able to get my version of qir-runner working (see [Issue #74](https://github.com/qir-alliance/qir-runner/issues/74)), but a colleague of mine who uses a MAC has a working version so the following question comes from the output of the MAC qir-runner.

The example comes from https://github.com/qir-alliance/pyqir/blob/main/examples/arithmetic.py which illustrates the use of custom external declarations "take_int" and "get_int". The conversion to QIR is attached here: [arithmetic.ll](https://github.com/qir-alliance/qir-runner/files/11712502/arithmetic.txt). Note that this was originally an *.ll but converted to *.txt so that it can be uploaded.

Running qir-runner with command on this file:
     ./qir-runner -f arithmetic.ll
produces the message:
     Error: "Failed to link some declared functions: get_int, take_int"

My question was: What does this error mean in terms of QIR development? Should we exclude such external functions in the python code? Then @swernli gave a helpful explanation of this to me, so I post the answer to my question here:

The error message is accurate: the functions “take_int” and “get_int” are custom functions declared in the sample code as an example of how to depend on custom external declarations and are not expected to be supported by other tools. Qir-runner supports the APIs listed in [qir-runner/README.md at main · qir-alliance/qir-runner · GitHub](https://github.com/qir-alliance/qir-runner/blob/main/runner/README.md), which corresponds to the API described in the QIR spec as well as a some extra quantum gate functions and intrinsics to support a broader (but not complete) set of Q# programs. The PyQIR library supports creating declarations to arbitrary external functions, and the sample you chose happens to be one that creates example functions that are not implemented anywhere. The error message from qir-runner is there to protect against this scenario, as was added in [Add Bindings Check to runner by swernli · Pull Request #11 · qir-alliance/qir-runner (github.com)](https://github.com/qir-alliance/qir-runner/pull/11) to avoid a problem where functions I the program that do not correspond to the implemented set will fail to link and cause a segmentation fault at runtime.

**Comment by swernli** [comment]
Thanks for filing, hopefully this can help others who run into similar issues. As mentioned above, any custom external functions in the QIR program that aren't part of the qir-runner supported set will produce this error, which is expected. Marking this issue as "closed" since this is normal behavior.
